apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spooner-sec
  labels:
    app: sec-tui
    version: "0.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sec-tui
      version: "0.1"
  template:
    metadata:
      labels:
        app: sec-tui
        version: "0.1"
    spec:
      containers:
        - name: spooner
          image: tushardwivedi/spooner_security:ngnx_html_v0.1-arm64