apiVersion: v1
kind: Pod
metadata:
  name: kuard-tls
spec:
  containers:
  - name: kuardCx-tls
    image: gcr.io/kuar.demo/kuard-amd64:blue
    imagePullPolicy: Always
    volumeMounts:
    - name: tls-secret
      mountPath: "/tls"
      readOnly: true
  volumes:
  - name: tls-secret
    secret:
      secretName: kuard-tls