apiVersion: v1
kind: Pod
metadata:
  name: lazysec
spec:
  containers:
  - name: lazy-ctx
    image: tushardwivedi/spooner_security:ngnx_html_v0.1-arm64
    imagePullPolicy: Always
  imagePullSecrets:
  - name: regcred
