# Example Job manifest for parallel pattern.
apiVersion: batch/v1
kind: Job
metadata:
  name: parallel
  labels:
    ch: jobs
spec:
  parallelism: 5
  completions: 10
  template:
    metadata:
      labels:
        ch: jobs
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:blue
        imagePullPolicy: Always
        command:
        - "/kuard"
        args:
        - "--keygen-enable"
        - "--keygen-exit-on-complete"
        - "--keygen-num-to-gen=10"
      restartPolicy: OnFailure