apiVersion: apps/v1
kind: Deployment
metadata:
  name: spooner-deployment
  labels:
    app: spooner-html
  namespace: default
  annotations:
    deployments.kubernetes.io/revision: "1"
spec:
  progressDeadlineSeconds: 60
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spooner-html
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "First time Deploy"
      labels:
        app: spooner-html
    spec:
      containers:
      - name: spooner-ctx
        image: tushardwivedi/spooner_security:ngnx_html_v0.1-arm64
        imagePullPolicy: IfNotPresent
    
  