# Example manifest for Creates a read-deployments Role.
apiVersion: rbac.kubernetes.k8s.io/v1
kind: Role
metadata:
  namespace: prod-backend
  name: read-deployments
rules:
- verbs: ["get", "watch", "list"]
  apiGroups: ["apps"]
  resources: ["deployments"]