apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      svc: cloud
  template:
    metadata:
      labels:
        svc: cloud
    spec:
      containers:
      - name: service-cloud
        image: tushardwivedi/html-docker-images:v0.3-amd64
#        image: tushardwivedi/html-docker-images:v0.3
        ports:
        - containerPort: 80