# Manifest for StorageClass on Docker Desktop
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ddsc
provisioner: docker.ip/hostpath
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false